name: uta-gms-frontend
static_sites:
  - build_command: npm run build
    catchall_document: index.html
    github:
      branch: master
      deploy_on_push: true
      repo: UTA-WESOME/uta-gms-frontend
    name: uta-gms-frontend
    source_dir: /